from datetime import datetime
def buy_write(name, contact, bought_laptops, AmountVAT , all_total):
         '''Creating the bill with required details for buying in writing mode'''
         date_and_time=datetime.now()
         with open (str(name)+str(contact)+".txt","w") as file:
                file.write("\n")
                file.write("\t \t \t \t RK LAPTOP SHOP BILL ")
                file.write("\n")
                file.write("\t \t \t \t *********************")
                file.write("\n")
                file.write("\n")
                file.write("\t \t \t Kamalpokhari, Kathmandi | Phone No: 9876547789 ")
                file.write("\n")
                file.write("\t \t \t ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
                file.write("\n")
                file.write("\n")
                file.write("****-----****-----****-----****-----****-----****-----****-----****-----****-----****-----****-----****-----****-----****-----****")
                file.write("\n")
                file.write("\n")
                file.write("\t  Laptop Details are:")
                file.write("\n")
                file.write("\t  ^^^^^^^^^^^^^^^^^^^")
                file.write("\n")
                file.write("\t Name of the customer: "+str(name))
                file.write("\n")
                file.write("\n")
                file.write("\t Contact number: "+str(contact))
                file.write("\n")
                file.write("\n")
                file.write("\t Date and  time of purchase: "+str(date_and_time))
                file.write("\n")
                file.write("\n")
                file.write("****-----****-----****-----****-----****-----****-----****-----****-----****-----****-----****-----****-----****-----****-----****")
                file.write("\n")
                file.write("\n")
                file.write("Purchase Detail are: ")
                file.write("\n")
                file.write("\n")
                file.write("====================================================================================================================================")
                file.write("\n")
                file.write("Item Name \t  Total Quantity  \t Unit Price \t \t  Total")
                file.write("\n")
                file.write("======================================================================================================================================")
                file.write("\n")
                for i in bought_laptops:
                    file.write(str(i[0])+ " \t"+ str(i[1])+"\t \t"+ str(i[2])+ "\t \t"+"$"+str(i[3]) + "\n")
                file.write("\n")
                file.write("========================================================================================================================================")
                file.write("\n")
                file.write("VAT Amount:" +str(AmountVAT))
                file.write("\n")
                file.write("Grand Total: $"+str(all_total)+"\n")
                file.write("\n")
                file.write("VAT Amount has been added to grand total"+"\n")
                file.write("\n")


def sell_write(name, contact,date_and_time, bought_laptops ,shipping_value, all_total):
         '''Creating the bill with required details for purchasing in writing mode'''
         with open (str(name)+str(contact)+".txt","w") as file:
                    file.write("\n")
                    file.write("\t \t \t \t RK LAPTOP SHOP BILL ")
                    file.write("\n")
                    file.write("\t \t \t \t *********************")
                    file.write("\n")
                    file.write("\n")
                    file.write("\t \t \t Kamalpokhari, Kathmandi | Phone No: 9876547789 ")
                    file.write("\n")
                    file.write("\t \t \t ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
                    file.write("\n")
                    file.write("\n")
                    file.write("****-----****-----****-----****-----****-----****-----****-----****-----****-----****-----****-----****-----****-----****-----****")
                    file.write("\n")
                    file.write("\n")
                    file.write("\t  Laptop Details are:")
                    file.write("\n")
                    file.write("\t  ^^^^^^^^^^^^^^^^^^^")
                    file.write("\n")
                    file.write("\n")
                    file.write("\t Name of the customer: "+str(name))
                    file.write("\n")
                    file.write("\n")
                    file.write("\t Contact number: "+str(contact))
                    file.write("\n")
                    file.write("\n")
                    file.write("\t Date and  time of purchase: "+str(date_and_time))
                    file.write("\n")
                    file.write("\n")
                    file.write("****-----****-----****-----****-----****-----****-----****-----****-----****-----****-----****-----****-----****-----****-----****")
                    file.write("\n")
                    file.write("\n")
                    file.write("Purchase Detail are: ")
                    file.write("\n")
                    file.write("\n")
                    file.write("====================================================================================================================================")
                    file.write("\n")
                    file.write("Item Name \t  Total Quantity  \t Unit Price \t \t  Total")
                    file.write("\n")
                    file.write("======================================================================================================================================")
                    for i in bought_laptops:
                        file.write(str(i[0])+ " \t"+str(i[1])+ " \t \t"+str(i[2])+ " \t \t"+"$"+str(i[3]))
                    file.write("\n")
                    file.write("-------------------------------------------------------------------------------")
                    file.write("\n")
                    if shipping_value:
                        file.write("Your Shipping Cost is: "+str(shipping_value)+"\n")
                        file.write("\n")
                        file.write("Grand Total: $"+str(all_total)+"\n")
                        file.write("\n")
                        file.write("Note: Shipping cost is added to the grand total"+"\n")
                    else:
                        file.write("Grand Total: $"+str(all_total))
